name: Execute Ansible scripts
on:
  pull_request:
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: pip install -r requirements.txt
      - run: python -m unittest
      - name: Deploy
        run: .github/scripts/deploy.sh
        env:
          VAULT_PASS: ${{ secrets.VAULT_PASS }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
